data:
  path:  data/comprehensive_cars/images/*.jpg
  test_path: data/comprehensive_cars/val/*.jpg
  fid_file: data/comprehensive_cars/fid_files/comprehensiveCars_256.npz
  random_crop: True
  img_size: 256
model:
  z_dim: 128
  z_dim_bg: 128
  decoder: simple
  discriminator: resnet_cond
  generator: simple
  background_generator: simple
  bounding_box_generator: simple
  neural_renderer: simple
  bounding_box_generator_kwargs:
    scale_range_min: [0.15, 0.12, 0.12]
    scale_range_max: [0.25, 0.2, 0.2]
    translation_range_min: [-0.7, -0.12, 0.]
    translation_range_max: [0.7, 0.12, 0.]
  decoder_kwargs:
    hidden_size: 256
    rgb_out_dim: 256
    n_blocks: 8
    skips: [4]
  generator_kwargs:
    range_v: [0.41667, 0.5]
    fov: 10
  neural_renderer_kwargs:
    input_dim: 256
    n_feat: 512
    use_rgb_skip: False
    use_norm: True
  background_generator_kwargs:
    rgb_out_dim: 256
    hidden_size: 128
    downscale_p_by: 8
    n_blocks: 3
    skips: []
training:
  out_dir:  out/cars/256/3
  batch_size: 32
  print_every: 10
  checkpoint_every: 500
  visualize_every: 500
  validate_every: 50000
  backup_every: 10000
  learning_rate: 0.0001
  learning_rate_d: 0.00007
  learning_rate_i: 0.0001
  model_selection_metric: fid_score
  model_selection_mode: minimize
  n_workers: 0
  logfile: train.log
  overwrite_visualization: False
  multi_gpu: false
  optimizer: RMSprop
  optimizer_kwargs: {}
  n_eval_images: 10000
  inv_start_iter : 100000
test:
  model_file: model.pt
  n_images: 20000
  take_generator_average: False
rendering:
  render_batch_size: 2 # interpolate -> 2 (fixed)
  mode: interpolate # train, inversion, test, interpolate
  render_dir: rendering_inversion
  render_inv_dir : rendering_inversion
  test_dir : test
  interpolate_dir : interpolate
  render_program: ['object_rotation'] #, 'interpolate_app', 'interpolate_shape'] 
