data:
  path: /data/cats/images/*.jpg
  celebA_center_crop: False
  afhq_center_crop: False
  fid_file: /data/cats/fid_files/cats_128.npz
  test_path: /data/cats/val/*.jpg
  img_size: 128
model:
  z_dim: 128
  z_dim_bg: 64
  decoder: simple
  discriminator: resnet_cond
  generator: simple
  background_generator: simple
  bounding_box_generator: simple
  neural_renderer: simple
  bounding_box_generator_kwargs:
    scale_range_min: [0.21, 0.21, 0.21]
    scale_range_max: [0.21, 0.21, 0.21]
    translation_range_min: [0., 0., 0.]
    translation_range_max: [0., 0., 0.]
    rotation_range: [0.375, 0.675]
  decoder_kwargs:
    hidden_size: 128
    rgb_out_dim: 256
    n_blocks: 8
    skips: [4]
  generator_kwargs:
    range_v: [0.4167, 0.5]
    fov: 10
  neural_renderer_kwargs:
    input_dim: 256
    n_feat: 256
    use_rgb_skip: True
    use_norm: False
  background_generator_kwargs:
    rgb_out_dim: 256
    hidden_size: 64
    downscale_p_by: 12
    n_blocks: 4
    skips: []
training:
  out_dir: out/cats/128/1
  batch_size: 32
  print_every: 10
  checkpoint_every: 500
  visualize_every: 500
  validate_every: 10000
  backup_every: 10000
  learning_rate: 0.0001
  learning_rate_d: 0.00007
  learning_rate_i: 0.0001
  model_selection_metric: fid_score
  model_selection_mode: minimize
  n_workers: 0
  logfile: train.log
  overwrite_visualization: False
  multi_gpu: False
  optimizer: RMSprop
  optimizer_kwargs: {}
  n_eval_images: 10000
  inv_start_iter : 100000
test:
  model_file: model.pt
  n_images: 20000
  take_generator_average: False
rendering:
  render_batch_size: 2 # interpolate -> 2 (fixed)
  mode: interpolate # train, inversion, test, interpolate
  render_dir: rendering_inversion
  render_inv_dir : rendering_inversion
  test_dir : test
  interpolate_dir : interpolate
  render_program: ['object_rotation'] #, 'interpolate_app', 'interpolate_shape'] 
